Simulation = "ServiceDrynx"
Servers = 6
Bf = 2
Suite = "bn256.G1"
Rounds = 1
Bandwidth = 100
Delay = 20
GroupByValues = [1]
TAGS = "vartime"
RunWait = "2h"

Hosts, NbrServers, NbrVNs, NbrDPs, NbrDPsPerServer, Proofs, Ranges, Obfuscation, OperationName, NbrInput, NbrOutput, DiffPEpsilon, DiffPDelta, DiffPSize, DiffPQuanta, DiffPScale, DiffPLimit, DiffPOpti, DPRows, MinData, MaxData, ThresholdGeneral, ThresholdOther, CuttingFactor
16, 3, 3, 10, 10, 1, 18, false, "sum", 1, 1, 0.0, 0.0, 0, 0.0, 0.0, 0.0, false, 1, 1, 2, 1.0, 1.0, 0